### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by yamacandy** [sssurvey/reader#102]
### Log in Page
----
As a user, I want to log in, so I can retrieve my subscriptions. 
As a user, I want to create a new account, so I can save the subscriptions I want.
As a user, I want to be able to connect with social media like FB or GG, so I can skip the register process.
As a user, I want to be able to see the password I typed, so I can confirm it is correct.

--------------------

Description:
User needs a login page, here is the flow:
Existing user>>> click icon open the app > input account and password (see and hide password) > log in
Existing user>>> click icon open the app>forgot password> new page
New user>>>click icon open the app > click create account/ continue with google / continue with facebook> putin account name and password> log in

----
Need to have:
same as figma
----
Acceptance:

----
Logo - top center
Input box - username/email
Input box - password  (see or unsee)
forget password - link to a new page
Log in button - jump to new page (home)
connect link - to google account 
connect link - to fb account 
create a new account - to a new page 

---------------
https://www.figma.com/file/hMrQ493fNcYpmDstGVNWHN/RSSSSSSSSS?node-id=5%3A2

**Comment by sssurvey** [comment]
working on branch https://github.com/sssurvey/reader/tree/enhancement-102-login-screen

**Comment by sssurvey** [comment]
Still need dark mode, follows devices dark mode settings at login page. After the login, the user should have the ability to change to light/dark mode. And the app should remember that the next time user launch the app.
